### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by shoujiaxin** [GrapeforGitHub/Feedback#10]
点开 https://github.com/marquistj13/TongjiThesis/issues/12 这个 issue 会 100% 闪退，这个 repo 的其他 issue 没发现这个问题

iPhone 8 Plus 12.0.1 - V2.1.0(126)

**Comment by derekcoder** [comment]
感谢反馈。会尽快修复。

**Comment by derekcoder** [comment]
这个问题在 V2.2.0 版本修复了，欢迎更新体验。感谢反馈。
