### ISSUE TITLE
Background theme

### ISSUE THREAD

**Issue by billdavidzyb** [GrapeforGitHub/Feedback#11]
Best tool for github ever! Could you please    provide theme switch for background color? It would be more compatible for reading. Thanks

iPhone X 12.0.1 - V2.1.0(126)

**Comment by derekcoder** [comment]
Hi @billdavidzyb, do you mean night mode?

**Comment by derekcoder** [comment]
I added night mode into development plan. I will let you know when it is progressing.

**Comment by derekcoder** [comment]
@derekcoder I am working on night mode currently. It should be okay to release this function in next version. Thanks for your patience.

**Comment by derekcoder** [comment]
This feature is implemented in v2.8.0. Please update and have a try. Thanks.

**Comment by billdavidzyb** [comment]
Awesome! I've tried it! Thx
