### ISSUE TITLE
看不到pr commits 的内容和 changes 

### ISSUE THREAD

**Issue by pigletfly** [GrapeforGitHub/Feedback#13]
iPhone 7 12.1 - V2.3.1(136)

**Comment by derekcoder** [comment]
感谢反馈。查看 Commit 详细信息的功能已经在开发计划中了。如果有新的进展，我会第一时间更新在这里。

**Comment by derekcoder** [comment]
@pigletfly V2.4.0 中实现你的建议。欢迎下载体验。再次感谢反馈。

**Comment by pigletfly** [comment]
Cool, blast fast
