### ISSUE TITLE
@头像不更新

### ISSUE THREAD

**Issue by yiukuenchu** [GrapeforGitHub/Feedback#16]
在电脑上更新了头像，app里刷新不出新头像🤔

iPhone X 12.1 - V2.3.1(136)

**Comment by derekcoder** [comment]
@yiukuenchu 已经发现这个问题了。这周会发版本，这个问题会在这个版本解决。感谢反馈！

**Comment by derekcoder** [comment]
@yiukuenchu V2.4.0 已经发布，修复了该问题。欢迎更新体验。
