### ISSUE TITLE
无法显示emoji

### ISSUE THREAD

**Issue by youngxhui** [GrapeforGitHub/Feedback#19]
对于一些commit是emoji的，无法显示

iPad Air 2 12.0.1 - V2.4.1(150)

**Comment by derekcoder** [comment]
@youngxhui 你好，可以麻烦你提供一个具体的例子吗？那样我比较快能定位问题。感谢反馈。

**Comment by youngxhui** [comment]
[这个仓库](https://github.com/Wevan/Repair/commits/master)

**Comment by derekcoder** [comment]
@youngxhui 收到，会在近期修复。如果有新的进展，我会更新在这里。

**Comment by derekcoder** [comment]
@youngxhui 该问题已经在版本 V2.5.0 中解决。请更新体验。再次感谢反馈。

**Comment by youngxhui** [comment]
> @youngxhui 该问题已经在版本 V2.5.0 中解决。请更新体验。再次感谢反馈。

已经更新 👍
