### ISSUE TITLE
首页问题

### ISSUE THREAD

**Issue by DarielChen** [GrapeforGitHub/Feedback#20]
首页刷新的时候数据不能及时更新 有时需要反复滑动页面

iPhone 6s 12.0 - V2.2.0(130)

**Comment by derekcoder** [comment]
@DarielChen 感谢反馈。请问下你的首页是指 News 页面吗？

**Comment by DarielChen** [comment]
对的 比如star数,有时明明有新的star 老的cell还是原来的star数

**Comment by derekcoder** [comment]
@DarielChen 明白了，会尽快修复。

**Comment by derekcoder** [comment]
@DarielChen 该问题已在 V2.5.0 中解决，请更新体验。再次感谢反馈。
