### ISSUE TITLE
近三天的贡献图没有点亮🚀

### ISSUE THREAD

**Issue by yiukuenchu** [GrapeforGitHub/Feedback#22]
最近三天的贡献图是灰色的呢，显示不正常。

iPhone X 12.1 - V2.5.0(165)

**Comment by derekcoder** [comment]
@yiukuenchu 感谢反馈。目前的贡献图还比较局限，看不到你个人对私有仓库的贡献。下面两张图，一张是我从网站中截取的你的个人贡献图，另外一张是我从Grape 应用中截取的你的贡献图。它们两个是一致的。

<img width="762" alt="screenshot 2018-11-30 at 9 30 50 am" src="https://user-images.githubusercontent.com/19852435/49262860-4298bf80-f483-11e8-82f0-185c9047282f.png">
<img width="576" alt="screenshot 2018-11-30 at 9 34 28 am" src="https://user-images.githubusercontent.com/19852435/49262861-4298bf80-f483-11e8-99e1-525303bdeebe.png">
