### ISSUE TITLE
修改图标

### ISSUE THREAD

**Issue by Pircate** [GrapeforGitHub/Feedback#24]
看了下最新的修改图标功能，请问是否支持上传图标修改？

iPhone 6s Plus 12.1 - V2.6.0(168)

**Comment by derekcoder** [comment]
@Pircate 有意思的想法，我要尝试下。不过可能还有个挑战：即使实现了，不知道 Apple 审核会不会让过。目前还没看到什么应用支持自己上传图片修改图标的。

**Comment by zhoudengfengderek** [comment]
@Pircate 我又仔细的想了下，还是不可以。因为你上传的图片没办法放到 Bundle 里，所以设置图标时没办法找到你上传的图片。

**Comment by derekcoder** [comment]
@Pircate 我又仔细的想了下，还是不可以实现。因为上传的图片没办法放到 Bundle 里。

**Comment by Pircate** [comment]
@derekcoder 那能不能内置多一些图标呢，现在的图标感觉跟 github 没啥关系😂

**Comment by derekcoder** [comment]
@Pircate 目前还主要专注在功能和优化上，后期会重新设计图标。

**Comment by derekcoder** [comment]
@Pircate 感谢建议。
