### ISSUE TITLE
contributions 与 GitHub 官网上不一致

### ISSUE THREAD

**Issue by Hivol** [GrapeforGitHub/Feedback#26]
contributions 的数量和图片都与 GitHub 不一致

iPhone 6s 12.1.1 - V2.6.0(168)

**Comment by derekcoder** [comment]
@Hivol 感谢反馈。目前这个功能有一个小缺陷，就是不能统计到私有仓库的 contributions。我比较了网页版你的个人 contributions 和 Grape 应用中的 contributions，发现是一致的。
<img width="866" alt="screenshot 2018-12-11 at 6 46 49 pm" src="https://user-images.githubusercontent.com/19852435/49795767-d2891400-fd75-11e8-85f6-6971242f7ece.png">
![img_2783](https://user-images.githubusercontent.com/19852435/49795771-d6b53180-fd75-11e8-9f1f-726357ca0f84.JPG)

**Comment by derekcoder** [comment]
@Hivol 如果你看到的不一致的话，应该就是你有私有仓库。

**Comment by Hivol** [comment]
感谢解答！

**Comment by Hivol** [comment]
![image](https://user-images.githubusercontent.com/31159723/50138849-e8995600-02da-11e9-8979-500f1c8acfde.png)
我发现在设置里打开private contributions就可以在app里正常显示了

**Comment by derekcoder** [comment]
@Hivol 感谢🙏告知。
