### ISSUE TITLE
Only 1 Organization is Displayed

### ISSUE THREAD

**Issue by danielmilner** [GrapeforGitHub/Feedback#36]
I am a member of 2 Organizations, but only 1 is being displayed on the Organization screen.

iPhone 7 Plus 12.1.2 - V2.9.1(211)

**Comment by derekcoder** [comment]
@danielmilner thank you for your feedback. I check first and let you know.

**Comment by derekcoder** [comment]
@danielmilner this is bug. I will fix this in next version. Thanks again for your feedback.

**Comment by derekcoder** [comment]
@danielmilner thanks for your feedback.
