### ISSUE TITLE
头像图片缓存似乎有问题

### ISSUE THREAD

**Issue by BrikerMan** [GrapeforGitHub/Feedback#38]
自己的头像都每次会重新加载，是不是没有缓存逻辑呀？

iPhone X 12.1.2 - V2.10.0(217)

**Comment by derekcoder** [comment]
@BrikerMan 目前采用的是内存缓存的策略。因为GitHub修改头像后路径不改变，所以没采用缓存到文件中的策略。我再想想怎么优化。

**Comment by BrikerMan** [comment]
建议使用缓存，然后每几次请求同一个头像后后台进程更新缓存。这样就可以避免每次打开都是空头像，虽然更新会滞后一点点，其实问题不大。

**Comment by derekcoder** [comment]
@BrikerMan 在 2.11.1 版本中已优化头像缓存策略。请及时更新体验。

**Comment by BrikerMan** [comment]
好一些了，thanks
