### ISSUE TITLE
Test is not fully visible

### ISSUE THREAD

**Issue by pandermatt** [GrapeforGitHub/Feedback#40]
![img_6730](https://user-images.githubusercontent.com/20790833/52564161-b5b79e00-2e03-11e9-94d8-7bf5a6df00ef.jpeg)

iPhone 7 12.1.3 - V2.11.0(222)

**Comment by derekcoder** [comment]
@pandermatt thank you for your feedback. I will fix this soon.

**Comment by derekcoder** [comment]
@pandermatt I fixed this issue in v2.11.1 already. Please update and have a try.

**Comment by pandermatt** [comment]
I’m on version 2.11.1(228) and it still looks like before

**Comment by derekcoder** [comment]
![simulator screen shot - iphone 7 - 2019-02-15 at 20 37 16](https://user-images.githubusercontent.com/19852435/52857285-a87f1400-3161-11e9-8a5e-697b3980922b.png)

@pandermatt This is iPhone 7 screenshot. I think you need update to App Store version with v2.11.1(229) and It will be okay.
