### ISSUE TITLE
Add option to open URLs directly in Safari

### ISSUE THREAD

**Issue by SuperTachyon** [GrapeforGitHub/Feedback#52]
iPad Pro (10.5-inch) 12.2 - V2.12.0(243)

**Comment by derekcoder** [comment]
Hi @SuperTachyon,

Currently Grape already support to open repo in Safari using Action. Please have a try.

**Comment by SuperTachyon** [comment]
Could you please elaborate what you mean by action? I’m looking for an option to tap on an external URL and open it in Safari instead of in Safari View Controller. Like the option in Githawk.

**Comment by SuperTachyon** [comment]
> Could you please elaborate what you mean by action? I’m looking for an option to tap on an external URL and open it in Safari instead of in Safari View Controller. Like the option in Githawk. @derekcoder 

The reason being that SVC doesn’t share cookie and cache with Safari. It’s annoying to, say click on cookie notice or sign in again for every website.

**Comment by derekcoder** [comment]
@derekcoder Got your meaning. You need an option to open external links using Safari. Am I right?

**Comment by derekcoder** [comment]
No problem. I will add this option in next version.

**Comment by SuperTachyon** [comment]
> No problem. I will add this option in next version.

Thanks a lot!
