### ISSUE TITLE
can’t see all repositories

### ISSUE THREAD

**Issue by designscience** [GrapeforGitHub/Feedback#53]
I appreciate the features of this app and in particular the fine display of code with color highlighting. 

Unfortunately there seems to be a limit on the number of branches that will be listed in the app for a repo. As a result I cannot choose my most recent branch making the app far less useful for my purposes.

Thank you
Stu

iPhone Xs 12.1.4 - V2.12.0(243)

**Comment by derekcoder** [comment]
Hi @designscience,

Could you provide me the repository for debugging?

**Comment by derekcoder** [comment]
Hi @designscience, I fixed this issue in v2.12.1. Please update and have a try.
