### ISSUE TITLE
经常不明原因的“网络请求失败”

### ISSUE THREAD

**Issue by ghost** [GrapeforGitHub/Feedback#6]
iOS 12.0 - V1.8.0(104)

**Comment by derekcoder** [comment]
你好，感谢反馈。为了方便定位错误，可以麻烦说下具体哪个页面会跳出“网络请求失败”的提示吗？

**Comment by Chibi-Doki** [comment]
以下情况会出现“网络请求失败”：

- 将程序放于后台一段时间后再次进入
- 刷新可能会出现
- 打开程序也可能出现

**Comment by derekcoder** [comment]
出现 “网络请求失败” 是因为有 Api 调用没有成功，初步判断可能跟网络有关系。这个 Issue 先开着，看看有没有更多的人有这个问题？

**Comment by derekcoder** [comment]
@ghost 没有更多人提出同样的问题，我先把这个 Issue 关了。如果你还有同样的问题，欢迎再提新的 Issue。
