### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by pigletfly** [GrapeforGitHub/Feedback#7]
Markdown 显示可以优化下，explore 希望能和网站一样按照语言过滤，很棒的应用

iPhone 7 12.0.1 - V2.0(121)

**Comment by derekcoder** [comment]
感谢反馈。Explore 是支持选择语言的，点击导航栏下面的按钮即可进入选择语言界面。关于markdown 显示问题，可以请问下你是指 readme？

**Comment by pigletfly** [comment]
这个过滤不太容易找到，markdown 现在显示的源码，我意思是是否可以渲染成结果？

**Comment by derekcoder** [comment]
对于过滤按钮不太明显问题，同意你的观点，我再想想怎么优化。对于 markdown 直接渲染结果问题，下个版本会解决。

**Comment by derekcoder** [comment]
makrdown 显示 readme 的问题已经在 v2.1.0 中修复。关于按钮不明显的问题，暂时我还没有想到更好的显示方式，我已经记录下来了。我先关闭这个 issue。

感谢反馈。
