### ISSUE TITLE
底层的tab menu导航图标不在垂直方向的中间

### ISSUE THREAD

**Issue by peprilus** [GrapeforGitHub/Feedback#8]
ipad 2018如此，不知道其他机型，强迫症的我弱弱地吐一下槽😝（调皮）

iPad 6 12.1 - V2.0(121)

**Comment by derekcoder** [comment]
感谢你的反馈！最近准备优化下 iPad 的显示问题。

**Comment by derekcoder** [comment]
已在 v2.1.0 版本中修复了该问题。感谢反馈。
