### ISSUE TITLE
一些改进与功能建议 👏👏

### ISSUE THREAD

**Issue by spencerwooo** [GrapeforGitHub/Feedback#9]
1. 能修改自己仓库里面的文件并直接 Push 到仓库
2. Issue 内容支持 Markdown 渲染

iPhone 7 Plus 12.0.1 - V2.1.0(126)

**Comment by spencerwoo98** [comment]
再加一个建议😂：增加仓库 README 的缓存，有时候 README 图片多加载很慢，缓存下来体验应该会更好点，之后 README 更新手动刷新就行。

**Comment by derekcoder** [comment]
Issue 已经在版本 V2.2.0 中支持 markdown 了。欢迎更新体验。

**Comment by spencerwooo** [comment]
牛逼！

**Comment by derekcoder** [comment]
感谢反馈。对于问题1，暂时还不在我的开发计划列表里，如果你很需要这个功能，麻烦你再单独开个 Issue，我暂时先把这个 Issue 关了。

**Comment by spencerwooo** [comment]
理解，暂时还没有对问题 1 的强烈需要，不过第二个 issue 页面的 Markdown 渲染解决了很开心，感谢～
